
package be.molowayi.beerSoapClient.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BeerServiceEndpoint", targetNamespace = "http://beerSoapService.molowayi.be/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BeerServiceEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns be.molowayi.beerSoapClient.client.Beer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBeerById", targetNamespace = "http://beerSoapService.molowayi.be/", className = "be.molowayi.beerSoapClient.client.GetBeerById")
    @ResponseWrapper(localName = "getBeerByIdResponse", targetNamespace = "http://beerSoapService.molowayi.be/", className = "be.molowayi.beerSoapClient.client.GetBeerByIdResponse")
    @Action(input = "http://beerSoapService.molowayi.be/BeerServiceEndpoint/getBeerByIdRequest", output = "http://beerSoapService.molowayi.be/BeerServiceEndpoint/getBeerByIdResponse")
    public Beer getBeerById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InvalidBeerException_Exception
     * @throws InvalidNumberException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "orderBeer", targetNamespace = "http://beerSoapService.molowayi.be/", className = "be.molowayi.beerSoapClient.client.OrderBeer")
    @ResponseWrapper(localName = "orderBeerResponse", targetNamespace = "http://beerSoapService.molowayi.be/", className = "be.molowayi.beerSoapClient.client.OrderBeerResponse")
    @Action(input = "http://beerSoapService.molowayi.be/BeerServiceEndpoint/orderBeerRequest", output = "http://beerSoapService.molowayi.be/BeerServiceEndpoint/orderBeerResponse", fault = {
        @FaultAction(className = InvalidBeerException_Exception.class, value = "http://beerSoapService.molowayi.be/BeerServiceEndpoint/orderBeer/Fault/InvalidBeerException"),
        @FaultAction(className = InvalidNumberException_Exception.class, value = "http://beerSoapService.molowayi.be/BeerServiceEndpoint/orderBeer/Fault/InvalidNumberException")
    })
    public void orderBeer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws InvalidBeerException_Exception, InvalidNumberException_Exception
    ;

}
